name: Lint Awesome List
on: [push]

jobs:
  awesome-lint:
    name: "Lint"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout repo"
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2.1.0
        name: "Setup Node"
        with:
          node-version: '14'
      - name: "Install awesome-lint"
        run: npm install -g awesome-lint
      - name: "Run awesome-lint"
        run: awesome-lint
